spring:
  application:
    name: microservice-api-gateway
    
server:
  port: 8050

logging:
 level:
  root: INFO

#注册到 eureka server配置

eureka: 
  client: 
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: true

#访问http://localhost:8050/routes，出现401，没有权限
#关闭权限验证
management: 
  security: 
    enabled: false