server:
  port: 8001

spring:
  application: 
    name: microservice-provider-user
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-demo
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
 
logging:
 level:
  root: INFO
  org.hibernate: INFO
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  
#自定义actuator的监控信息  
info:
  app: @project.artifactId@
  encoding: @project.build.sourceEncoding@
  java:
    version: @java.version@
    source: @java.version@
    target: @java.version@
      