server:
  port: 8010

#spring.application.name：指定注册到Eureka Server上的名称

spring:
  application: 
    name: microservice-consumer-movie

logging: 
 level:
  root: INFO

microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001