server:
  port: 8761

logging:
 level:
  root: INFO

#eureka server配置

#registerWithEureka：表示是否将自己注册到Eureka Server，默认为true
#fetchRegistry：表示是否从Eureka Server获取注册信息，默认是true。
#因为这里是单节点，所以上面两个属性就设置为false
#defaultZone：服务查询和注册使用的地址，多个地址可以使用,分割
eureka: 
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
user:
  userServiceUrl: http://localhost:8000/