server:
  port: 8010

#spring.application.name：指定注册到Eureka Server上的名称

spring:
  application: 
    name: microservice-consumer-movie


#eureka.instance.prefer-ip-address：表示将自己的IP注册到Eureka Server
#如果不配置该属性，则表示注册微服务所在操作系统的hostname到Eureka Server     
eureka: 
  client: 
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      #这样就可以把服务注册到高可用的Eureka Server上，
      #不过写一个地址也可以，因为Eureka Server之间会同步，建议把集群地址都写上
      defaultZone: http://peer1:8761/eureka/,http://peer1:8761/eureka/
  instance: 
    prefer-ip-address: true

logging:
 level:
  root: INFO
  
user:
  userServiceUrl: http://localhost:8000/